---
- name: Install Trivy on AWS Instance
  hosts: aws_instances
  become: yes  # Ensure that tasks are run as root

  tasks:
    - name: Add Trivy GPG key
      ansible.builtin.apt_key:
        url: "https://aquasecurity.github.io/trivy-repo/deb/public.key"
        state: present

    - name: Add Trivy repository
      ansible.builtin.apt_repository:
        repo: "deb https://aquasecurity.github.io/trivy-repo/deb {{ ansible_lsb.codename }} main"
        state: present

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Trivy
      ansible.builtin.apt:
        name: trivy
        state: present
